### ISSUE TITLE
Change: Next.jsか静的サイトジェネレータを使う

### ISSUE THREAD

**Issue by tasuren** [nattyan-tv/dinosaur-homepage#2]
# 概要
Next.jsか何か静的サイトジェネレータを使用して、マークダウンからHTMLを生成できるようにする。
こうすることで、作業効率が格段にあがる。
ウェブサイトのデザインを気にしない場合は、ドキュメントのウェブサイトを作るためのものである[Docusaurus](https://docusaurus.io)を使うのも良いかもしれない。(とても簡単にできる。)
もし、上に書いたどれかをするのなら、ウェブサーバーでHTMLを提供しているところを、GitHub ActionsとPagesを使い、自動でHTMLを生成してウェブサイトを更新するようにしてしまった方がより便利だと思う。

**Comment by nattyan-tv** [comment]
Markdownで書けるなら凄い幸せになれる気がする
GitHub Actionsと静的サイトジェネレーター用いたGitHub Pagesへの公開をした事がないけど、難しくない事を信じたい...

**Comment by tasuren** [comment]
簡単簡単、コピペでもできる。
`.githib`にどのような環境でなんてコマンドを実行するかを書いた一つのファイルを追加するだけ。
Pull Requestしていい？

**Comment by nattyan-tv** [comment]
あ、pr大歓迎ぃ！

**Comment by tasuren** [comment]
Pagesを設定からONにしたのちなんかpushしてみて。
で、https://nattyan-tv.github.io/dinosaur-homepage でなんか表示されるのを確認したら、Pagesの設定からドメイン名を入力する。
そのあとドメインの設定で色々やる。(これは後で教える、それか自分で調べてね。)

**Comment by tasuren** [comment]
あ
https://github.com/nattyan-tv/dinosaur-homepage/blob/c245ab228043b2d13693b23170169bc82950c721/.github/workflows/deploy.yml#L6
ここmainからmasterにしてくれない？
このリポジトリメインブランチがmasterなの忘れてた。
じゃないと更新されない。

**Comment by tasuren** [comment]
実装したため、closeする。
